const db=supabase.createClient('https://demo.invalid','demo-local-only');
let state={products:[],units:[],sales:[],saleItems:[],suppliers:[],customers:[],credits:[],purchases:[],cash:[],sessions:[],settings:null,business:null};
let saleCart=[],buyCart=[],saleLayout=localStorage.getItem('demo_sale_layout')||'auto';
const $=id=>document.getElementById(id), money=n=>'RD$'+Number(n||0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2}), num=v=>Number(v||0), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function loginUser(){await db.auth.signInWithPassword({email:$('email')?.value||'demo@portfolio.local',password:'demo'});enterApp()}
async function logout(){location.reload()}
async function enterApp(){$('login')?.classList.add('hidden');$('app')?.classList.remove('hidden');await refreshAll()}
async function refreshAll(){try{$('sync').textContent='Actualizando demo...';const [p,u,s,si,sup,c,cr,pu,cm,cs,se,b]=await Promise.all([db.from('products').select('*').eq('active',true).order('name'),db.from('product_units').select('*').eq('active',true),db.from('sales').select('*').order('created_at',{ascending:false}),db.from('sale_items').select('*'),db.from('suppliers').select('*').eq('active',true),db.from('customers').select('*').eq('active',true),db.from('credit_entries').select('*').order('created_at',{ascending:false}),db.from('purchases').select('*').order('purchased_at',{ascending:false}),db.from('cash_movements').select('*').order('created_at',{ascending:false}),db.from('cash_sessions').select('*').order('opened_at',{ascending:false}),db.from('app_settings').select('*').limit(1),db.from('businesses').select('*').limit(1)]);state={products:p.data||[],units:u.data||[],sales:s.data||[],saleItems:si.data||[],suppliers:sup.data||[],customers:c.data||[],credits:cr.data||[],purchases:pu.data||[],cash:cm.data||[],sessions:cs.data||[],settings:se.data?.[0]||{},business:b.data?.[0]||{name:'Control Colmado · DEMO'}};renderAll();$('sync').textContent='Demo local · '+new Date().toLocaleTimeString()}catch(e){$('sync').textContent='Demo local'}}
function unitsFor(pid){return state.units.filter(u=>u.product_id===pid&&u.active)}
function defaultUnit(pid){return unitsFor(pid)[0]||null}
function renderAll(){if($('businessName'))$('businessName').textContent=state.business?.name||'Control Colmado · DEMO';if($('heroBusiness'))$('heroBusiness').textContent=state.business?.name||'Control Colmado · DEMO';renderDashboard();renderSaleProducts();renderCart();renderProducts();renderPurchaseSelectors();renderPurchaseCart();renderSuppliers();renderCredits();renderCash();renderReports();renderSalesHistory();renderPurchases();loadSettingsUi()}
function today(){return new Date().toLocaleDateString('en-CA')}
function renderDashboard(){let sales=state.sales.filter(s=>s.status!=='anulada'&&String(s.created_at||'').slice(0,10)===today()),total=sales.reduce((a,s)=>a+num(s.total),0),debt=state.credits.reduce((a,x)=>a+(x.entry_type==='cargo'?num(x.amount):-num(x.amount)),0),low=state.products.filter(p=>num(p.stock)<=num(p.min_stock)).length,open=state.sessions.find(s=>s.status==='abierta');$('mSalesToday').textContent=money(total);$('mSalesCount').textContent=sales.length+' operaciones';$('heroToday').textContent=money(total);$('mDebt').textContent=money(Math.max(0,debt));$('mLow').textContent=low;$('mCash').textContent=open?'Abierta':'Cerrada';$('mCashSub').textContent=open?'sesión demo activa':'abre caja para iniciar'}
function productPrice(p,u){return num(u?.sale_price??p?.sale_price)}
function renderSaleProducts(){let q=($('saleSearch')?.value||'').toLowerCase(),rows=state.products.filter(p=>!q||String(p.name).toLowerCase().includes(q)||String(p.shortcut||'').toLowerCase().includes(q)||String(p.barcode||'').includes(q));let grid=saleLayout==='grid'||(saleLayout==='auto'&&innerWidth>1050);$('saleProducts').className=grid?'sale-product-grid':'';$('saleProducts').innerHTML=rows.map(p=>{let u=defaultUnit(p.id),price=productPrice(p,u);return grid?`<div class="sale-card"><b class="product-title">${esc(p.name)}</b><span class="muted small">Stock ${num(p.stock)} · ${esc(p.unit_type||'unidad')}</span><b>${money(price)}</b><div class="sale-card-actions"><input id="q_${p.id}" type="number" value="1" min="0.001" step="0.001"><span></span><button class="btn primary" onclick="addSale('${p.id}')">Agregar</button></div></div>`:`<div class="product-row"><div><b>${esc(p.name)}</b><div class="muted small">Stock ${num(p.stock)} · ${money(price)}</div></div><select id="u_${p.id}">${unitsFor(p.id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><input id="q_${p.id}" type="number" value="1" min="0.001" step="0.001"><button class="btn primary" onclick="addSale('${p.id}')">Agregar</button></div>`}).join('')||'<div class="empty">Sin productos</div>';['List','Grid','Auto'].forEach(x=>{let e=$('saleView'+x);if(e)e.classList.toggle('active',saleLayout===x.toLowerCase())})}
function setSaleLayout(x){saleLayout=x;localStorage.setItem('demo_sale_layout',x);renderSaleProducts()}
function saleScanEnter(e){if(e.key==='Enter'){let p=state.products.find(x=>x.barcode===e.target.value.trim());if(p)addSale(p.id)}}
function addSale(pid){let p=state.products.find(x=>x.id===pid),u=$('u_'+pid)?.value||defaultUnit(pid)?.id,q=num($('q_'+pid)?.value||1),unit=state.units.find(x=>x.id===u);if(!p||q<=0)return;saleCart.push({product:p,unit,quantity:q,price:productPrice(p,unit)});renderCart()}
function renderCart(){let total=saleCart.reduce((a,x)=>a+x.quantity*x.price,0);$('cart').innerHTML=saleCart.map((x,i)=>`<div class="cartline"><div><b>${esc(x.product.name)}</b><div class="muted small">${x.quantity} × ${money(x.price)}</div></div><div class="right"><b>${money(x.quantity*x.price)}</b><button class="icon-btn" onclick="saleCart.splice(${i},1);renderCart()">×</button></div></div>`).join('')||'<div class="empty">Agrega productos a la venta</div>';$('cartTotal').textContent=money(total)}
function clearSale(){saleCart=[];renderCart()}
async function openCheckout(){if(!saleCart.length)return alert('Agrega al menos un producto.');let items=saleCart.map(x=>({product_id:x.product.id,unit_id:x.unit?.id,quantity:x.quantity}));await db.rpc('complete_sale',{p_items:items,p_amount_paid:saleCart.reduce((a,x)=>a+x.quantity*x.price,0),p_payment_method:'efectivo'});clearSale();await refreshAll();alert('Venta demo guardada localmente.')}
function renderProducts(){let q=($('productSearch')?.value||'').toLowerCase(),r=state.products.filter(p=>!q||p.name.toLowerCase().includes(q));$('productTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Producto</th><th>Stock</th><th>Precio</th><th>Estado</th></tr></thead><tbody>${r.map(p=>`<tr><td><b>${esc(p.name)}</b><div class="muted small">${esc(p.barcode||p.shortcut||'')}</div></td><td>${num(p.stock)} ${esc(p.unit_type||'')}</td><td>${money(p.sale_price)}</td><td><span class="pill ${num(p.stock)<=num(p.min_stock)?'amber':'green'}">${num(p.stock)<=num(p.min_stock)?'Bajo':'OK'}</span></td></tr>`).join('')}</tbody></table></div>`}
async function createProduct(){let name=$('pName').value.trim();if(!name)return;await db.rpc('create_product_with_units',{p_name:name,p_barcode:$('pBarcode').value.trim(),p_shortcut:$('pShortcut').value.trim(),p_unit_type:$('pBaseUnit').value,p_initial_stock:num($('pStock').value),p_min_stock:num($('pMin').value),p_cost_price:num($('pBaseCost').value),p_sale_price:num($('pSalePrice').value),p_track_stock:true});$('productMsg').textContent='Producto demo guardado.';await refreshAll()}
function renderPurchaseSelectors(){if(!$('buyProduct'))return;$('buySupplier').innerHTML='<option value="">Sin proveedor</option>'+state.suppliers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('buyProduct').innerHTML=state.products.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');updateBuyUnits()}
function updateBuyUnits(){let pid=$('buyProduct')?.value;if(!$('buyUnit'))return;$('buyUnit').innerHTML=unitsFor(pid).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');updateBuyCost()}
function updateBuyCost(){let p=state.products.find(x=>x.id===$('buyProduct')?.value);if(p)$('buyCost').value=num(p.cost_price)||''}
function addPurchaseLine(){let p=state.products.find(x=>x.id===$('buyProduct').value),u=state.units.find(x=>x.id===$('buyUnit').value),q=num($('buyQty').value),cost=num($('buyCost').value);if(!p||q<=0)return;buyCart.push({product:p,unit:u,quantity:q,cost});renderPurchaseCart()}
function renderPurchaseCart(){if(!$('purchaseCart'))return;let t=buyCart.reduce((a,x)=>a+x.quantity*x.cost,0);$('purchaseCart').innerHTML=buyCart.map((x,i)=>`<div class="cartline"><div><b>${esc(x.product.name)}</b><div class="small muted">${x.quantity} ${esc(x.unit?.name||'')}</div></div><div><b>${money(x.quantity*x.cost)}</b> <button class="icon-btn" onclick="buyCart.splice(${i},1);renderPurchaseCart()">×</button></div></div>`).join('')||'<div class="empty">Compra vacía</div>';$('purchaseTotal').textContent=money(t)}
async function registerPurchase(){if(!buyCart.length)return alert('Agrega mercancía.');let total=buyCart.reduce((a,x)=>a+x.quantity*x.cost,0);await db.from('purchases').insert({supplier_id:$('buySupplier').value||null,purchased_at:new Date().toISOString(),total,amount_paid:num($('buyPaid').value)||total,payment_status:'pagada',invoice_number:$('buyInvoice').value||'DEMO'});buyCart=[];renderPurchaseCart();await refreshAll();$('purchaseMsg').textContent='Compra demo registrada.'}
function renderPurchases(){if(!$('purchaseHistory'))return;$('purchaseHistory').innerHTML=state.purchases.map(x=>`<div class="cartline"><div><b>${esc(x.invoice_number||'Compra')}</b><div class="small muted">${String(x.purchased_at||'').slice(0,10)}</div></div><b>${money(x.total)}</b></div>`).join('')||'<div class="empty">Sin compras</div>'}
async function createSupplier(){let n=$('sName').value.trim();if(!n)return;await db.from('suppliers').insert({name:n,phone:$('sPhone').value,address:$('sAddress').value,active:true});await refreshAll();$('supplierMsg').textContent='Proveedor demo guardado.'}
function renderSuppliers(){if(!$('supplierTable'))return;$('supplierTable').innerHTML=state.suppliers.map(x=>`<div class="cartline"><div><b>${esc(x.name)}</b><div class="small muted">${esc(x.phone||'')}</div></div><span class="pill green">Activo</span></div>`).join('')||'<div class="empty">Sin proveedores</div>';$('supplierDebt').textContent=money(state.purchases.reduce((a,x)=>a+Math.max(0,num(x.total)-num(x.amount_paid)),0))+' pendiente'}
async function createCustomer(){let n=$('cName').value.trim();if(!n)return;await db.from('customers').insert({name:n,phone:$('cPhone').value,address:$('cAddress').value,credit_limit:num($('cLimit').value),active:true});await refreshAll();$('customerMsg').textContent='Cliente demo guardado.'}
function balance(cid){return state.credits.filter(x=>x.customer_id===cid).reduce((a,x)=>a+(x.entry_type==='cargo'?num(x.amount):-num(x.amount)),0)}
function renderCredits(){if(!$('creditTable'))return;let total=state.customers.reduce((a,c)=>a+Math.max(0,balance(c.id)),0);$('creditTotal').textContent=money(total);$('creditTable').innerHTML=state.customers.map(c=>`<div class="cartline"><div><b>${esc(c.name)}</b><div class="small muted">${esc(c.phone||'')}</div></div><b>${money(Math.max(0,balance(c.id)))}</b></div>`).join('')||'<div class="empty">Sin clientes</div>'}
function renderCash(){if(!$('cashState'))return;let open=state.sessions.find(x=>x.status==='abierta'),ins=state.cash.filter(x=>x.movement_type==='entrada').reduce((a,x)=>a+num(x.amount),0),outs=state.cash.filter(x=>x.movement_type==='salida').reduce((a,x)=>a+num(x.amount),0);$('cashState').textContent=open?'Abierta':'Cerrada';$('cashEstimated').textContent=money((open?num(open.opening_amount):0)+ins-outs);$('cashIn').textContent=money(ins);$('cashOut').textContent=money(outs);$('cashOpenClose').textContent=open?'Cerrar caja':'Abrir caja';$('cashMovements').innerHTML=state.cash.slice(0,8).map(x=>`<div class="cartline"><div>${esc(x.description||x.category||'Movimiento')}</div><b>${x.movement_type==='salida'?'-':'+'}${money(x.amount)}</b></div>`).join('')||'<div class="empty">Sin movimientos</div>'}
async function cashOpenClose(){let open=state.sessions.find(x=>x.status==='abierta');if(open){await db.from('cash_sessions').update({status:'cerrada',closed_at:new Date().toISOString()}).eq('id',open.id)}else{await db.from('cash_sessions').insert({status:'abierta',opening_amount:1500,opened_at:new Date().toISOString()})}await refreshAll()}
async function cashMovement(type){let v=prompt(type==='entrada'?'Monto del ingreso demo':'Monto del gasto demo','100');if(!v)return;await db.from('cash_movements').insert({movement_type:type,amount:num(v),category:type==='entrada'?'ingreso':'gasto',description:'Movimiento demo',created_at:new Date().toISOString()});await refreshAll()}
function renderReports(){if(!$('rSales'))return;let sales=state.sales.filter(x=>x.status!=='anulada'),total=sales.reduce((a,x)=>a+num(x.total),0),cost=state.saleItems.reduce((a,x)=>a+num(x.cost_price)*num(x.quantity),0),debt=state.customers.reduce((a,c)=>a+Math.max(0,balance(c.id)),0);$('rSales').textContent=money(total);$('rSalesCount').textContent=sales.length+' ventas';$('rCost').textContent=money(cost);$('rProfit').textContent=money(total-cost);$('rPurchases').textContent=money(state.purchases.reduce((a,x)=>a+num(x.total),0));$('rDebt').textContent=money(debt);$('rSupplierDebt').textContent=money(state.purchases.reduce((a,x)=>a+Math.max(0,num(x.total)-num(x.amount_paid)),0));$('rLow').textContent=state.products.filter(p=>num(p.stock)<=num(p.min_stock)).length;$('rProducts').textContent=state.products.length}
function renderSalesHistory(){if(!$('salesHistory'))return;$('salesHistory').innerHTML=state.sales.slice(0,12).map(s=>`<div class="cartline"><div><b>Venta #${esc(s.sale_number)}</b><div class="small muted">${String(s.created_at||'').replace('T',' ').slice(0,16)} · ${esc(s.payment_method||'efectivo')}</div></div><div><b>${money(s.total)}</b> <span class="pill ${s.status==='anulada'?'red':'green'}">${esc(s.status||'completada')}</span></div></div>`).join('')||'<div class="empty">Sin ventas</div>'}
function settingsTab(n){document.querySelectorAll('.settings-menu button').forEach(b=>b.classList.toggle('active',b.dataset.setting===n));document.querySelectorAll('.settings-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===n))}
function loadSettingsUi(){if(!$('setBusiness'))return;$('setBusiness').value=state.business?.name||'Control Colmado · DEMO';$('accountEmail').textContent='demo@portfolio.local · datos únicamente en este navegador';$('bkProducts').textContent=state.products.length;$('bkSales').textContent=state.sales.length;$('bkCustomers').textContent=state.customers.length;$('bkSuppliers').textContent=state.suppliers.length;let theme=localStorage.getItem('demo_theme')||'system';$('pcTheme').value=theme;applyTheme(theme)}
async function saveBusiness(){let n=$('setBusiness').value.trim()||'Control Colmado · DEMO';if(state.business?.id)await db.from('businesses').update({name:n}).eq('id',state.business.id);$('businessMsg').textContent='Nombre guardado solo en esta demo.';await refreshAll()}
function saveSettings(){$('settingsMsg').textContent='Configuración demo guardada localmente.'}
function applyTheme(t){document.documentElement.classList.toggle('pc-dark',t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme:dark)').matches))}
function saveLocalUi(){let t=$('pcTheme')?.value||'system';localStorage.setItem('demo_theme',t);applyTheme(t);saleLayout=$('pcSaleLayout')?.value||saleLayout;localStorage.setItem('demo_sale_layout',saleLayout);document.documentElement.classList.toggle('pc-compact',$('pcCompact')?.checked);renderSaleProducts()}
function download(name,text,type='application/json'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportBackup(){download('control-colmado-demo.json',JSON.stringify(state,null,2))}
function exportInventoryCsv(){download('inventario-demo.csv','Producto,Stock,Precio\n'+state.products.map(p=>`"${String(p.name).replaceAll('"','""')}",${p.stock},${p.sale_price}`).join('\n'),'text/csv')}
function exportSalesCsv(){download('ventas-demo.csv','Venta,Total,Estado\n'+state.sales.map(s=>`${s.sale_number},${s.total},${s.status}`).join('\n'),'text/csv')}
function openResetDialog(){if(confirm('¿Restablecer los datos ficticios de la demo?'))window.__DEMO_LOCAL_DB__?.reset()}
function editSale(){}
function voidSale(){}
function creditCharge(){}
function creditPayment(){}
function supplierPayment(){}
function adjustStock(){}
function beep(){}

document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('main section').forEach(s=>s.classList.toggle('active',s.id==='page-'+b.dataset.page));$('title').textContent=b.textContent.replace(/^[^A-Za-zÁÉÍÓÚÑ]+/,'').trim()}));
document.querySelectorAll('#reportRange button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#reportRange button').forEach(x=>x.classList.toggle('active',x===b));renderReports()}));
window.addEventListener('DOMContentLoaded',()=>{if($('email'))$('email').value='demo@portfolio.local';if($('password'))$('password').value='demo';loadSettingsUi()});
